### ISSUE TITLE
downloading empty zip file from widget site

### ISSUE THREAD

**Issue by wallentx** [dimitri-koenig/uebersicht-widget-for-google-cal#1]
Hey, just a heads up, if you try to download this from http://tracesof.net/uebersicht-widgets/#google-cal it just grabs the empty .zip file from your repo. 

Direct download link from the ubersicht page ->  https://raw.githubusercontent.com/dimitri-koenig/uebersicht-widget-for-google-cal/master/uebersicht-widget-for-google-cal.widget.zip

**Comment by dimitri-koenig** [comment]
Sorry :-)

Fixed it. Now it actually should contain a file ;-)
