### ISSUE TITLE
google calendar xml feeds have been discontinued

### ISSUE THREAD

**Issue by ghost** [dimitri-koenig/uebersicht-widget-for-google-cal#2]
hi, im new to ubersicht, trying to add multiple calendars to this widget, which calls for the xml feed address from Google Calendar. Google has ended the XML feeds since November 2015. Do you have another way to add calendars to this widget? thnx.

**Comment by dimitri-koenig** [comment]
Using ical or the google calendar api would be possible. But unfortunately I'm not using uebersicht anymore myself. It was fun in the beginning but that's it... Sorry...
