### ISSUE TITLE
Getting Google Calendar XML feed url

### ISSUE THREAD

**Issue by lumincui** [dimitri-koenig/uebersicht-widget-for-google-cal#3]
It seems that this widget needs xml feed url but just iCal and Http format can be found in my Google Calendar, so that there are some change need to do for this?

**Comment by lumincui** [comment]
XML feeds will no longer be available in Google Calendar as of Nov. 18, 2015

**Comment by dimitri-koenig** [comment]
I'm sorry but I don't longer maintain this repo. So updating is not planned in any way.
